---
- name: mail - Setup mail alerts
  template:
    src: mail.j2
    dest: {{ monit_includes }}/mail
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0640
  notify: restart monit
  when: monit_mail_enabled
