---
- name: web - Setup webinterface
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0640
  notify: restart monit
